micronaut:
  application:
    name: sesNotificationLambda

online:
  reporting:
    from: "test-source@email.com"
    to: "test-tagret@email.com"

offline:
  reporting:
    from: "test-source@email.com"
    to: "test-tagret@email.com"
  backend: dynamoDb
