name: "Tag git"

on:
  push:
    branches:
      - main

jobs:
  tag:
    name: "Create git tag"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
          WITH_V: true
